swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    #transactions 
  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Monthly Transactions 
      description: API for fetching monthly transactions by account
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            type: array
            $ref: '#/definitions/Account'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        "404":
          description: Not Found
        '500':
          description: Internal Server Error
  /transactions/{id}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: A Transaction Details
      description: API for fetching a transaction details
      parameters:
        - in: path
          name: TransactionId
          type : string
          description: Transaction Id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        "404":
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update category and notes for a transaction
      description: Update category and notes for a transaction
      parameters:
        - in: path
          name: TransactionId
          type : string
          description: Transaction Id
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/TransactionDetails'
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        "404":
          description: Not Found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
#mon code       
  Account:
    type: object
    properties:  
      accountId:
        type: string
      balance:
        type: number
      transactions:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              description: Id of the transaction
            date:
              type: string
              format: date
              description: Date of the transaction
            description: 
              type: string
              description: Description of the transaction
            amount:
              type: number
              description: Amount of the transaction
            balance:
              type: number
              description: Balance of the transaction
    required:
      - id 
      - date 
      - description
      - amount
      - balance
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Id of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description: 
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance:
        type: number
        description: Balance of the transaction
      type:
        type: string
        description: Type of the transaction  
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes of the transaction
  TransactionDetails:
    type: object
    properties:
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes of the transaction
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
        description: status code
      message:
        type: string
        description: confirm message

